services:
  server:
      container_name: aba_server
      build: ./server
      command:  bash -c "service apache2 start && python manage.py makemigrations && python manage.py migrate && python3 manage.py loaddata db.json && python manage.py runserver 0.0.0.0:8000"
      restart: always 
      volumes:
        - ./server/aba/:/aba/
        - ./server/aba/:/var/www/html
      ports:
        - '80:80'
        - '8000:8000'
        - '443:443'
      depends_on:
        - db
        - es
      env_file:
      - ./.env.dev
  db:
    container_name: aba_db
    image: mysql:8
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: db_django
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: ghjcnjQ21
    restart: always
    volumes:
       - ./mysql-data:/var/lib/mysql
       - ./:/home
  es:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
