# Generated by Django 3.2.12 on 2023-12-29 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок баннера')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='banner_image/', verbose_name='Изображение баннера')),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('href', models.TextField(blank=True, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Банер',
                'verbose_name_plural': 'Банеры',
            },
        ),
    ]
